library(shiny)
library(shinydashboard)
library(shinydashboardPlus)

library(highcharter)
library(xts)
library(lubridate)

library(shinycssloaders)
library(shinyWidgets)
library(htmltools)

library(tidyr)
library(rlang)

library(dplyr)
library(readr)
library(RCurl)

library(shinyjs)
library(formattable)
library(sparkline)
# library(DT)

# library(networkD3)
library(visNetwork)

library(RColorBrewer)
library(reshape2)

library(shinyhelper)
library(shinyBS)

library(purrr)

##########################################
# Reading the data
##########################################
## 7776 x 7777 
## 108 hens * 72 combination 
## Generated by the time series of the chickens using dynamic time warping (we called these matrices Distmat)
# if(!exists("Distmat11")) {
  # Distmat11 <- read_delim("www/data/Distmat11.csv", ",", escape_double = FALSE, trim_ws = TRUE)
# }
  
# un_exprs <- as.matrix(Distmat11 %>% select(-1))
# exprs <- t(un_exprs)
# eucl_dist=dist(exprs, method = 'euclidean')
# hie_clust=hclust(eucl_dist, method = 'complete')
# dend <- as.dendrogram(hie_clust)
# plot(dend)

## 108 x 109
## 108 hens
## association index. how many times one hen follows another hen within 5 seconds 
## to cross popholes (formula like this: AI(AB)=AB/(A+B-AB), 
## where A is the number of registrations of bird A, B is the number of 
## registrations of bird B, and AB is the number of co-occurrences of birds A and B)
# if(!exists("aimat11")) {
aimat11 <- read_delim("www/data/aimat11.csv", ";", escape_double = FALSE, trim_ws = TRUE, col_types = cols()) %>%
  as.data.frame()
# }

# un_exprs <- as.matrix(aimat11 %>% select(-1))
# exprs <- t(un_exprs)
# eucl_dist=dist(exprs, method = 'euclidean')
# hie_clust=hclust(eucl_dist, method = 'complete')
# plot(hie_clust)
# dend <- as.dendrogram(hie_clust)
# plot(dend)
# 
# cutreee <- cutree(hie_clust, k = 5)

aimat12 <- read_delim("www/data/aimat12.csv", ";", escape_double = FALSE, trim_ws = TRUE, col_types = cols()) %>%
  as.data.frame()

aimat13 <- read_delim("www/data/aimat13.csv", ";", escape_double = FALSE, trim_ws = TRUE, col_types = cols()) %>%
  as.data.frame()

aimat14 <- read_delim("www/data/aimat14.csv", ";", escape_double = FALSE, trim_ws = TRUE, col_types = cols()) %>%
  as.data.frame()

## Based on the distmats I created dendrograms and cluster labelled all hens accordingly 
## (column called mycl), for the aimats we extracted the network measures 
## "X1", "HenID", "Pen", "Bird", "Betweenness", "Centrality", "Status", "Community", "mycl"
# if(!exists("networkmeasures_DTWcluster")) {
networkmeasures_DTWcluster <- read_delim("www/data/networkmeasures_DTWcluster.csv", ",", escape_double = FALSE, trim_ws = TRUE, col_types = cols()) %>%
  rename(Cluster = mycl) %>%
  select(-X1) %>%
  mutate(
    Community = as.character(Community),
    Pen_ID = Pen - 10,
    Pen_Number = Pen - 10,
    Community_ID = case_when(
      Community %in% c("11.1", "12.1", "13.1", "14.1") ~ 1,
      Community %in% c("11.2", "12.2", "13.2", "14.2") ~ 2,
      Community %in% c("11.3", "12.3", "13.3", "14.3") ~ 3,
      Community %in% c("11.4", "12.4", "13.4", "14.4") ~ 4,
      Community %in% c("11.5", "13.5", "14.5") ~ 5,
      Community %in% c("14.6") ~ 6,
      TRUE ~ 1
    )
  )%>%
  group_by(Pen) %>%
  mutate(
    Cluster = if_else(Pen == 11, 
      case_when(
        Cluster == 1 ~ 4,
        Cluster == 2 ~ 3,
        Cluster == 3 ~ 2,
        Cluster == 4 ~ 1,
        TRUE ~ 5
      ), Cluster
    )
  ) %>% ungroup()
# }

##########################################
# Variables
##########################################
networkLayoutsList <- c(
  # "Bipartite graphs" = "layout_as_bipartite", 
  # "Star-shape" = "layout_as_star", 
  # "Tree-like" = "layout_as_tree", 
  # "GEM" = "layout_with_gem", 
  # "Large Graph" = "layout_with_lgl", 
  # "Sugiyama" = "layout_with_sugiyama",
  "Circle" = "layout_in_circle",
  "Automatically" = "layout_nicely",
  "Grid" = "layout_on_grid",
  "Sphere" = "layout_on_sphere",
  "Randomly" = "layout_randomly",
  "Davidson-Harel" = "layout_with_dh",
  "Fruchterman-Reingold" = "layout_with_fr",
  "Graphopt " = "layout_with_graphopt",
  "Kamada-Kawai" = "layout_with_kk",
  "Multidimensional scaling" = "layout_with_mds"
)

networkSmoothType <- c(
  "Dynamic" = "dynamic",
  "Continuous" = "continuous",
  "Discrete" = "discrete",
  "DiagonalCross" = "diagonalCross",
  "StraightCross" = "straightCross",
  "Horizontal" = "horizontal",
  "Vertical" = "vertical",
  "CurvedCW" = "curvedCW",
  "CurvedCCW" = "curvedCCW",
  "CubicBezier" = "cubicBezier"
)

pensNumberName <- birdNodesName <- c(setNames(11:14, sapply(1:4, function(x) {sprintf("Pen %s", x)})))

nodesColorByProperties <- c(
  "Cluster" = "Cluster",
  # "Pen" = "Pen_ID",
  "Community" = "Community_ID"
)

nodesPropertiesGroupBy <- c(
  "Cluster" = "Cluster", "Community_ID" = "Community"
)

nodesReorderBy <- c(
  "Cluster" = "Cluster", "Community" = "Community_ID", "Bird" = "id", "Betweenness" = "Betweenness", "Centrality" = "Centrality"
)

fontAwesomeIconsBirds <- list(
  "1" = list(name = "star", code = "f005"),
  "2" = list(name = "circle", code = "f111"),
  "3" = list(name = "square", code = "f0c8"),
  "4" = list(name = "certificate", code = "f0a3"),
  "5" = list(name = "cloud", code = "f0c2"),
  "6" = list(name = "bell", code = "f0f3"),
  "7" = list(name = "stop", code = "f04d"),
  "8" = list(name = "diamond", code = "f219"),
  "9" = list(name = "heart", code = "f004"),
  "10" = list(name = "asterisk", code = "f069"),
  "11" = list(name = "location-arrow", code = "f124"),
  "12" = list(name = "cog", code = "f013")
)

nodesColorByProperties2 <- setNames(names(nodesColorByProperties), unname(nodesColorByProperties))

birdsClusterColorPalette <- brewer.pal(9, "Set1")
# birdsClusterColorPaletteLeaflet <- colorFactor("Set1", domain = 1:9)

contacts <- list(
  list(name = "Yamenah G&#243;mez", short_institution = "Center for Proper Housing: Poultry and Rabbits (ZTHZ), University of Bern, Switzerland", institution = c("Center for Proper Housing: Poultry and Rabbits (ZTHZ), Division of Animal Welfare, VPH Institute, University of Bern, Burgerweg 22, 3052 Zollikofen, Switzerland."), email = "yamenah.gomez@vetsuisse.unibe.ch", website = "", picture = "yamenah.jpg", description = "", cv = ""),
  list(name = "John Berezowski", short_institution = "Veterinary Public Health Institute (VPHI), University of Bern, Switzerland", institution = c("Veterinary Public Health Institute, Vetsuisse, University of Bern, Switzerland."), email = "john.berezowski@vetsuisse.unibe.ch", website = "", picture = "john.jpg", description = "", cv = ""),
  list(name = "Yandy Abreu Jorge", short_institution = "National Centre for Animal and Plant Health, Cuba", institution = c("National Centre for Animal and Plant Health, Cuba."), email = "yajorge@censa.edu.cu", website = "", picture = "yandy.jpg", description = "", cv = ""),
  list(name = "Sabine Gabriele Gebhardt-Henrich", short_institution = "Center for Proper Housing: Poultry and Rabbits (ZTHZ), University of Bern, Switzerland", institution = c("Center for Proper Housing: Poultry and Rabbits (ZTHZ), Division of Animal Welfare, VPH Institute, University of Bern, Burgerweg 22, 3052 Zollikofen, Switzerland."), email = "sabine.gebhardt@vetsuisse.unibe.ch", website = "", picture = "sabine_gabriele.jpg", description = "", cv = ""),
  list(name = "Sabine Voegeli", short_institution = "Center for Proper Housing: Poultry and Rabbits (ZTHZ), University of Bern, Switzerland", institution = c("Center for Proper Housing: Poultry and Rabbits (ZTHZ), Division of Animal Welfare, VPH Institute, University of Bern, Burgerweg 22, 3052 Zollikofen, Switzerland."), email = "sabine.voegeli@blw.admin.ch", website = "", picture = "user-female.png", description = "", cv = ""),
  list(name = "Ariane Stratmann", short_institution = "Center for Proper Housing: Poultry and Rabbits (ZTHZ), University of Bern, Switzerland", institution = c("Center for Proper Housing: Poultry and Rabbits (ZTHZ), Division of Animal Welfare, VPH Institute, University of Bern, Burgerweg 22, 3052 Zollikofen, Switzerland."), email = "ariane.stratmann@vetsuisse.unibe.ch", website = "", picture = "ariane.jpg", description = "", cv = ""),
  list(name = "Michael Jeffrey Toscano", short_institution = "Center for Proper Housing: Poultry and Rabbits (ZTHZ), University of Bern, Switzerland", institution = c("Center for Proper Housing: Poultry and Rabbits (ZTHZ), Division of Animal Welfare, VPH Institute, University of Bern, Burgerweg 22, 3052 Zollikofen, Switzerland."), email = "michael.toscano@vetsuisse.unibe.ch", website = "", picture = "michael.jpg", description = "", cv = ""),
  list(name = "Bernhard Voelkl", short_institution = "Division of Animal Welfare, VPHI, University of Bern, Switzerland", institution = c("Division of Animal Welfare, VPH Institute, University of Bern, Switzerland."), email = "bernhard.voelkl@vetsuisse.unibe.ch", website = "", picture = "bernhard.jpg", description = "", cv = "")
)

tsColnames <- c(setNames(sapply(1:72, function(x) {sprintf("%s", x)}), sapply(1:72, function(y) {sprintf("Day %s", y)})))

timeSequence <- seq.POSIXt(
  ISOdate(2020, 1, 1, 7, 25, 0, tz = "UTC"),
  ISOdate(2020, 1, 1, 17, 0, 0, tz = "UTC"),
  "10 sec"
)

levelColorPaletteSparkline <- c("1" = "#A4BAE8", "2" = "#ED9C88", "3" = "#FFCC7F", "4" = "#87CA8B", "5" = "#B2D47F")
graphExtraColor <- c("Total" = "#434348", "other" = "#8085E9")
##########################################
# Messages
##########################################
loadingMessage <- "Loading... please be patient"

##########################################
# Import functions
##########################################
source("functions.R")
source("www/modules/chickenNetworkModule.R")
source("www/modules/chickenProjectModule.R")
source("www/modules/chickenTimeSeriesModule.R")
source("www/modules/chickenDownloadModule.R")